
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import TransitionProvider from "./components/transitionprovider"
import { Inter } from 'next/font/google'; 
 



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
   <html lang="en"> 
      <link rel="preconnect" href="https://fonts.googleapis.com"/> 
      <link rel="preconnect" href="https://fonts.gstatic.com" /> 
      <link href="https://fonts.googleapis.com/css2?family=ADLaM+Display&display=swap" rel="stylesheet"/> 
      <body 

      >
        <div className="w-screen h-150 bg-gradient-to-b from-blue-50 to-red-100 ">
         
         

           <TransitionProvider>{children}</TransitionProvider>
          
        </div>
      </body>
    </html>
  );
}

