
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import TransitionProvider from "./components/transitionprovider"
import { Nunito_Sans } from 'next/font/google'
import { Analytics } from "@vercel/analytics/next"

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito',
  weight: ['200', '300', '400', '600', '700', '800', '1000'],
  display: 'swap',
})
 



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
   <html lang="en" className={nunitoSans.variable} > 
     
      <body  

      >
        <div className="w-screen h-150 bg-gradient-to-b from-blue-50 to-red-100 ">
         
         

           <TransitionProvider>{children} <Analytics /></TransitionProvider>
          
        </div>
      </body>
    </html>
  );
}

