
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import TransitionProvider from "./components/transitionprovider"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body

      >
        <div className="w-screen h-150 bg-gradient-to-b from-blue-50 to-red-100 ">
         
         

           <TransitionProvider>{children}</TransitionProvider>
          
        </div>
      </body>
    </html>
  );
}
